### ISSUE TITLE
When start multiple project at once cli don't recognize actual active one

### ISSUE THREAD

**Issue by lrnzmonaco** [lcfd/trak#22]
Start a new tracker when there is currently an active one it prints a different name on the screen ([link](https://asciinema.org/a/axaKHf0etsAYXnrvmKCjsJ99v.js)).

The problem, I think, it's that the cli messages are generated based on the `trak start <arg>`, if a project is currently active it should be generated based on that.

When running `trak stop` the original name returns. 

In the JSON file, only the original project name is saved.
It seems to not compromise the functionality of the app but I think it's good to give it a check.

**Comment by lcfd** [comment]
Hi @lrnzmonaco ,

This should be already fixed and in main, check #11 
It's not deployed on pypi, I wanted to add something more to 0.0.3.
